Quanlysach/Controllers/BookstoreController.cs
using Quanlysach.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quanlysach.Controllers
{
    public class BookstoreController : Controller
    {
        QLBANSACHEntities1 database= new QLBANSACHEntities1();
        private List<SACH> LaySachMoi(int soluong)
        {
            //Sx theo ngày cập nhập giảm dần, lấy theo biến soluong. Chuyen sang dang danh sach
            return database.SACHes.OrderByDescending(sach => sach.Ngaycapnhat).Take(soluong).ToList();
        }
        // GET: Bookstore
        public ActionResult Index()
        {
            var dsSachMoi = LaySachMoi(13);
            return View(dsSachMoi);
        }
        public ActionResult LayChuDe()
        {
            var dsChuDe = database.CHUDEs.ToList();
            return PartialView(dsChuDe);
        }
        public ActionResult LayNhaXuatBan()
        {
            var dsNhaXB = database.NHAXUATBANs.ToList();
            return PartialView(dsNhaXB);
        }
        public ActionResult SPTheoChuDe(int id)
        {
            //partial
            var dsSachTheoChuDe = database.SACHes.Where(sach => sach.MaCD == id).ToList();
            return PartialView("Index", dsSachTheoChuDe);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var dsSachNXB = database.SACHes.Where(sach => sach.MaNXB == id).ToList();
            return View("Index", dsSachNXB);
        }
        public ActionResult Details(int id)
        {
            var sach = database.SACHes.FirstOrDefault(s => s.Masach == id);
            return View(sach);
        }
    }
}

Quanlysach/Views/Bookstore/Details.cshtml
@using Quanlysach.Models
@model SACH
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thông tin chi tiết sách</h2>

<div class="row">
    <div class="offset-md-1 col-md-4">
        <img style="width:100%" src="~/Images/@Model.Hinhminhhoa" alt=" " />
    </div>
    <div class="col-md-6 details">
        <h3>Tên sách: @Model.Tensach</h3>
        <p style="text-align:justify">
            <span style="font-weight:bold">Mô tả:</span>@Model.Mota
        </p>
        <p class="price">
            Giá bán: <span style="color:red;font-size:30px;">@Model.Dongia VNĐ</span>
        </p>
        <a class="btn btn-primary" href="@Url.Action("ThemSanPhamVaoGio","GioHang", new {MaSP= Model.Masach})">
            Thêm vào giỏ
        </a>
    </div>
</div>

Quanlysach/Views/Bookstore/Index.cshtml
@using Quanlysach.Models

@model IEnumerable<Quanlysach.Models.SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    @foreach (var sach in Model)
    {
        <div class="card col-sm-4 col-md-4 col-lg-4 d-flex align-items-stretch book-section">
            <a href="@Url.Action("Details","Bookstore", new {id= sach.Masach})">
                <img class="card-img-top book-picture" src="~/Images/@sach.Hinhminhhoa" alt="Card image" />

            </a>
            <div class="card-body">
                <h4 class="card-title">@sach.Tensach</h4>
                <p class="card-text">@sach.Dongia</p>
            </div>
        </div>
    }
</div>

Quanlysach/Views/Bookstore/LayChuDe.cshtml
@using Quanlysach.Models
@model IEnumerable<CHUDE>
<div class="title">Chủ đề sách</div>
<ul class="list-group">
    @foreach (var chude in Model)
    {
        <a href="@Url.Action("SPTheoChuDe","Bookstore",new {id=chude.MaCD})" class="list-group-item list-group-item-action " >
            @chude.TenChuDe
        </a>
    }
</ul>

Quanlysach/Views/Bookstore/LayNhaXuatBan.cshtml
@using Quanlysach.Models
@model IEnumerable<NHAXUATBAN>
<div class="title">NHÀ XUẤT BẢN</div>
<ul class="list-group">
    @foreach (var nxb in Model)
    {
        <a href="@Url.Action("SPTheoNXB", "Bookstore", new { id=nxb.MaNXB })"
           class="list-group-item list-group-item-action">
            @nxb.TenNXB
        </a>
    }
</ul>